spring.application.name=spring1
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${db_url}
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}

server.port=8081

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.data.redis.host=${redis_host:localhost}
spring.data.redis.port=${redis_port:6379}

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000


bucket4j.enabled=false
bucket4j.cache-to-use=redis-lettuce

spring.cache.type=redis

rate-limit.capacity=${RATE_LIMIT_CAPACITY:60}
rate-limit.time=${RATE_LIMIT_TIME:1}
rate-limit.unit=${RATE_LIMIT_UNIT:minutes}

api-cache.ttl-seconds=${API_CACHE_TTL_SECONDS:300}
